### PR TITLE
Finally a working test case for memory leak (with fix)

### PR DESCRIPTION
**Pull request by glasswalk3r**
Hello David,

Finally I was able to dedicate some time to hunt down this bug I mentioned in the past and wasn't able to properly demonstrate.

It seems that using Test::Weaken is not a good choice (or I wasn't able to use it correctly) due the usage of lexical `%machines` and `%states`, which makes difficult to check them. But I was able to implement two additional test cases showing the issue.

One uses Devel::Gladiator to show the references counting being increased for FSA::States objects (and here is the problem). I implemented an object to properly look for what I trying to demonstrate (references to packages), so I filtered out everything else. You want to check t/pingpong-leak.t for that.

The other test t/pingpong-leak2.t is to check RSS usage on Linux (the test should definitly verify if the OS running the test is not Linux and skiping it in this case but it is not yet implemented). I execute the "ping-pong" routine a couple of times to "warm up", then start checking if RSS was increased. This test **is not perfect**, I tried to create a child process to monitor RSS and use Unix sockets for communication with parent process to avoid messing around values while checking RSS but somehow Test::More is increasing scalars usage over time if the test is repeated more than once.

The fix is implemented from lines 388 to 392 in Rules.pm. Just uncommented the loop to weaken references that all FSA::States objects have between them. You can also uncomment `use Test::More` and the calls to `note()` to have additional messages when testing with `prove -l -v -m`. It is interesting to see the difference when the objects are being properly removed by the garbage collector and the order when that happens without and with the `weaken()` usage.

Unfortunately the test "t/graph.t" is failing. Don't know the reason, the output of text graph seems to be correct but it is on a different order and with some addtional spaces than the expected output. Since it didn't touched that part, don't know what happened here. The test will fail even with my "patch" commented.

In eager to know if these things are working properly know. Please let me know.

My best regards,

Alceu

### CODE REVIEW

**Comment by theory** [comment]
Thanks a million, your identification of the location of the leak allowed me to finally reproduce it in a test. And yeah, I should have spotted it before! Anyway, please confirm that e390d39 fixes the issue for you, and then I'll push out a new release.

**Comment by theory** [comment]
v0.33 is on its way to CPAN with this and a few other fixes. Thanks again!

**Comment by glasswalk3r** [comment]
A little bit late for a feedback, but your code is ready to go. :-)
I updated version 0.35, it passed all your tests, including those that I created based on `pingpong.t` tests script. Also it passed the leak test on my own distribution (Siebel::Srvrmgr).
Glad that worked!

**Comment by theory** [comment]
Awesome, thank you! I'll release v0.36 with some compatibility and test fixes today.

**Comment by theory** [comment]
Er, I mean v0.35.

**Pull request closed without merging**
